esphome:
  name: t5_light
  friendly_name: T5 Light
  platformio_options:
    upload_speed: 115200

esp8266:
  board: esp01_1m
  restore_from_flash: true

api:
  password: !secret tft_light_api_password

ota:
  - platform: esphome
    password: "d9369f8e84ccd8355eb330fe37e8f3dd"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.1.111
    gateway: 192.168.1.1
    subnet: 255.255.255.0
  ap:
    ssid: "T5 Light AP"
    password: "hahaha1234"

logger:
  level: DEBUG

time:
  - platform: sntp
    id: esphome_time

captive_portal:

web_server:
  port: 80


switch:
  - platform: gpio
    id: nursery_light_relay
    name: "Nursery Light Relay"
    pin:
      number: GPIO0
      inverted: true
    restore_mode: RESTORE_DEFAULT_ON
